# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z010clg400-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/ugrads/d/dmimar382/lab8/lab8.cache/wt [current_project]
set_property parent.project_path /home/ugrads/d/dmimar382/lab8/lab8.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
read_verilog -library xil_defaultlib /home/ugrads/d/dmimar382/lab8/sr_latch.v
synth_design -top sr_latch -part xc7z010clg400-1
write_checkpoint -noxdef sr_latch.dcp
catch { report_utilization -file sr_latch_utilization_synth.rpt -pb sr_latch_utilization_synth.pb }
